# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Rob Enns'
tagline:             'Mostly Bacon'
description:         ''
url:                 http://rpe.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              'Rob Enns'
  url:               https://twitter.com/barque

# Custom vars
github:
  repo:           https://github.com/rpe/rpe.github.io
