name: Rob's Blog
markdown: redcarpet
pygments: true

redcarpet:
  extensions: [smart]
  
# Permalinks
permalink:        pretty

# Setup
title:            'Rob Enns'
tagline:          'Mostly Bacon'
description:      ''
url:              http://rpe.me

author:
  name:           'Rob Enns'
  url:            https://twitter.com/barque

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rpe/rpe.github.io
