# Dependencies
highlighter:         rouge

# Permalinks
permalink:           pretty
#relative_permalinks: true

gems: [jekyll-paginate]

# Setup
title:               'Rob Enns'
tagline:             'Mostly Bacon'
description:         'Coffee, bikes, cameras, and bacon. Mostly bacon.'
url:                 http://rpe.me
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              'Rob Enns'
  url:               https://twitter.com/barque

# Custom vars

github:
  user:           rpe
  url:            https://github.com/rpe
  repo:           https://github.com/rpe/rpe.github.io

twitter:
  user:           barque
  url:            https://twitter.com/barque
